language: node_js
node_js:
  - node

jobs:
  include:
    - addons:
        chrome: stable
      env: BROWSER=ChromeCi
    - addons:
        firefox: latest
      env: BROWSER=Firefox

services:
  - xvfb

cache:
  yarn: true
  npm: true

after_script:
  - node_modules/.bin/codecov

branches:
  only:
    - master
